### PR TITLE
Add communities used at AuvernIX

### PR DESCRIPTION
**Pull request by ledeuns**
We use large and extended communities.

### CODE REVIEW

**Comment by teunvink** [comment]
Those lines starting with `soo` will never match anything.

**Comment by ledeuns** [comment]
Oh, ok I did not realized extended communities were not supported. Sorry :)

**Comment by teunvink** [comment]
Not yet, but it's something we should be supporting. I'll open an issue so we won't forget it.

**Comment by teunvink** [comment]
Large and extended communities are now supported, so I added them.

**Comment by ledeuns** [comment]
Thank you Teun ! 👍

**Pull request merged**
