### PR TITLE
as38195.txt

### PR DESCRIPTION
**Pull request by timoid**
AS38195 BGP communities

### CODE REVIEW

**Comment by teunvink** [comment]
Large communities aren't fully supported yet. When they will be, syntax will be identical to the normal communities. So `nnn` instead of `*`.

**Comment by teunvink** [comment]
Thanks!

**Comment by timoid** [comment]
np. thanks also :)

**Comment by teunvink** [comment]
Large and extended communities are supported now, so I added a modified version of your initial file.

**Pull request merged**
