### PR TITLE
Update as13058.txt

### PR DESCRIPTION
**Pull request by csch42**
Fixed moar typos 🙄 and added externally visible large communities

### CODE REVIEW

**Comment by teunvink** [comment]
This will not work. `nnnn` would match <any number> followed by `n`. You most likely want `nnn` on that last line.

**Comment by csch42** [comment]
> On 6. Oct 2022, at 10:08, Teun Vink ***@***.***> wrote:
> 
> 
> This will not work. nnnn would match followed by n. You most likely want nnn on that last line.
> 
> 

I see. How can I fix that - now that I have already committed it? (I am not a user of GIT ...)
Or can you - before merging it?

Thanks,

	Clemens

**Comment by teunvink** [comment]
I fixed it, should be ok now.

**Comment by csch42** [comment]
> I fixed it, should be ok now.
> 
> 
Thanks

	-c

**Pull request merged**
